### ISSUE TITLE
安装插件运行报错

### ISSUE THREAD

**Issue by vowor** [site-chenwei/jpush-phonegap-plugin-vendor-channel#1]
你好，方便咨询下这个插件怎么用吗？   我这按照文档的方式安装了jpush-phonegap-plugin-vendor-channel运行时报错，提示没有jpush的包，然后我安装jpush-phonegap-plugin插件，但是没法实现离线推送，而且安装jpush-phonegap-plugin插件提示插件冲突

**Comment by site-chenwei** [comment]
你把报错截图发一下我看看

**Comment by vowor** [comment]
![QQ图片20220328100032](https://user-images.githubusercontent.com/25870084/160313970-dd88bf50-878d-49ef-97ea-3d1d7d6dc500.png)
好的，谢谢指导

**Comment by site-chenwei** [comment]
看起来像是gradle引入依赖有些问题，你把App模块build.gradle截图一下

**Comment by vowor** [comment]
![Uploading QQ图片20220328141912.png…]()

**Comment by vowor** [comment]
![QQ图片20220328141912](https://user-images.githubusercontent.com/25870084/160337820-52aadcbd-1512-4c1b-9e2e-f80e4d510081.png)

**Comment by site-chenwei** [comment]
你的cordova版本是多少，从这个build.gradle能看出来是插件安装的时候的钩子函数没执行成功，所以APP里面依赖没成功添加

**Comment by vowor** [comment]
![QQ图片20220328142446](https://user-images.githubusercontent.com/25870084/160338463-4593fe8c-1483-4d5c-b37a-6b7637d4423b.png)
cordova版本：11.0.0

**Comment by site-chenwei** [comment]
在你执行安装插件的命令前，你的项目根目录下有push_config.json和agconnect-services.json这两个文件吗

**Comment by vowor** [comment]
platform/android下的根目录还是  ionic的根目录？

**Comment by site-chenwei** [comment]
项目根目录，在你的ionic项目下，和platform同级

**Comment by vowor** [comment]
噢噢   明白了   我搞错了   我放到platform/android下面去了    谢谢指导

**Comment by site-chenwei** [comment]
好，那你把插件移除掉再添加把，添加的时候关注下控制台输出，我写了控制台输出提示钩子是否执行成功

**Comment by vowor** [comment]
恩恩   好的   我先试试

**Comment by vowor** [comment]
现在可以运行了，包也都加载进去了，但是现在还是只能打开APP的时候才能收到消息，离线的就不行了，   极光推送上面也配置了APPID和Secret   ，  目前我只配置了小米的和华为的消息推送   其它的都留空了   不知道是不是这个的原因呢？

**Comment by site-chenwei** [comment]
应该不是，得看一下应用启动日志和极光控制台的集成信息看看厂商通道启用成功没，GitHub沟通不方便，你加我微信**********吧

**Comment by vowor** [comment]
好的  谢谢   麻烦你了

**Comment by site-chenwei** [comment]
问题已解决，请使用者一定按照Readme中所写的步骤执行，并保证生产打包、测试打包时均使用在各大厂商平台配置过得证书进行打包，否则将会出现厂商通道无法启用的问题！
